name: 'Datadog Notify'
description: 'Sends Event to Datadog via api call'
author: ben@cloudposse.com
branding:
  icon: 'alert-triangle'
  color: 'blue'

inputs:
  api_key:
      description: "Datadog API Key"
      required: true
  title:
    required: true
    description: "Title of the event"
  text:
    required: true
    description: "Description of the event"
  tags:
    required: true
    description: "Space separated list of Tags for the event, we auto append hostname:$(hostname)"
  alert_type:
     required: true
     description: "Type of the event, one of: error,warning,info,success,user_update,recommendation,snapshot"
     default: "info"

runs:
  using: "composite"
  steps:
    - id: Notify Datadog
      shell: bash
      run: |
        export DATADOG_API_KEY=${{ inputs.api_key }}
        chmod +x ./datadog-notify.sh
        ./datadog-notify.sh "${{ inputs.title }}" "${{ inputs.text }}" "${{ inputs.tags }}" "${{ inputs.alert_type }}"

